/******************************************************************************
* File Name: cycfg_gatt_db.c
*
* Description:
* BLE device's GATT database and device configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.90.0.2529
*
*******************************************************************************
* Copyright 2024 Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
******************************************************************************/

#include "cycfg_gatt_db.h"
#include "wiced_bt_uuid.h"
#include "wiced_bt_gatt.h"

/******************************************************************************
* GATT server definitions
******************************************************************************/

const uint8_t gatt_database[] = 
{
    /* Primary Service: Generic Access */
    PRIMARY_SERVICE_UUID16 (
            HDLS_GAP,
            __UUID_SERVICE_GENERIC_ACCESS),
        /* Characteristic: Device Name */
        CHARACTERISTIC_UUID16 (
                HDLC_GAP_DEVICE_NAME,
                HDLC_GAP_DEVICE_NAME_VALUE,
                __UUID_CHARACTERISTIC_DEVICE_NAME,
                GATTDB_CHAR_PROP_READ,
                GATTDB_PERM_READABLE),
        /* Characteristic: Appearance */
        CHARACTERISTIC_UUID16 (
                HDLC_GAP_APPEARANCE,
                HDLC_GAP_APPEARANCE_VALUE,
                __UUID_CHARACTERISTIC_APPEARANCE,
                GATTDB_CHAR_PROP_READ,
                GATTDB_PERM_READABLE),

    /* Primary Service: Generic Attribute */
    PRIMARY_SERVICE_UUID16 (
            HDLS_GATT,
            __UUID_SERVICE_GENERIC_ATTRIBUTE),

    /* Primary Service: Battery */
    PRIMARY_SERVICE_UUID16 (
            HDLS_BAS,
            __UUID_SERVICE_BATTERY),
        /* Characteristic: Battery Level */
        CHARACTERISTIC_UUID16 (
                HDLC_BAS_BATTERY_LEVEL,
                HDLC_BAS_BATTERY_LEVEL_VALUE,
                __UUID_CHARACTERISTIC_BATTERY_LEVEL,
                GATTDB_CHAR_PROP_READ | GATTDB_CHAR_PROP_NOTIFY,
                GATTDB_PERM_READABLE),
            /* Descriptor: Characteristic Presentation Format */
            CHAR_DESCRIPTOR_UUID16 (
                    HDLD_BAS_BATTERY_LEVEL_CHAR_PRESENTATION_FORMAT,
                    __UUID_DESCRIPTOR_CHARACTERISTIC_PRESENTATION_FORMAT,
                    GATTDB_PERM_READABLE),
            /* Descriptor: Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (
                    HDLD_BAS_BATTERY_LEVEL_CLIENT_CHAR_CONFIG,
                    __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION,
                    GATTDB_PERM_READABLE | GATTDB_PERM_WRITE_REQ),
};

/* Length of the GATT database */
const uint16_t gatt_database_len = sizeof(gatt_database);

/******************************************************************************
* GATT Initial Value Arrays
******************************************************************************/
 
uint8_t app_gap_device_name[] = {'B', 'M', 'S', '_', 'P', 'S', 'O', 'C', '6', '3', '\0',};
uint8_t app_gap_appearance[] = {0x00, 0x03,};
uint8_t app_bas_battery_level[] = {0x00,};
uint8_t app_bas_battery_level_char_presentation_format[] = {0x00, 0x00, 0x00, 0x00, 0x01, 0x00,
    0x00,};
uint8_t app_bas_battery_level_client_char_config[] = {0x00, 0x00,};
 
/******************************************************************************
* GATT Lookup Table
******************************************************************************/
 
gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[] =
{
    {
        HDLC_GAP_DEVICE_NAME_VALUE,                      /* attribute handle */
        MAX_LEN_GAP_DEVICE_NAME,                         /* maxlen */
        10,                                              /* curlen */
        app_gap_device_name,                             /* attribute data */
    },
    {
        HDLC_GAP_APPEARANCE_VALUE,                       /* attribute handle */
        MAX_LEN_GAP_APPEARANCE,                          /* maxlen */
        2,                                               /* curlen */
        app_gap_appearance,                              /* attribute data */
    },
    {
        HDLC_BAS_BATTERY_LEVEL_VALUE,                    /* attribute handle */
        MAX_LEN_BAS_BATTERY_LEVEL,                       /* maxlen */
        1,                                               /* curlen */
        app_bas_battery_level,                           /* attribute data */
    },
    {
        HDLD_BAS_BATTERY_LEVEL_CHAR_PRESENTATION_FORMAT, /* attribute handle */
        MAX_LEN_BAS_BATTERY_LEVEL_CHAR_PRESENTATION_FORMAT,/* maxlen */
        7,                                               /* curlen */
        app_bas_battery_level_char_presentation_format,  /* attribute data */
    },
    {
        HDLD_BAS_BATTERY_LEVEL_CLIENT_CHAR_CONFIG,       /* attribute handle */
        MAX_LEN_BAS_BATTERY_LEVEL_CLIENT_CHAR_CONFIG,    /* maxlen */
        2,                                               /* curlen */
        app_bas_battery_level_client_char_config,        /* attribute data */
    },
};

/* Number of Lookup Table entries */
const uint16_t app_gatt_db_ext_attr_tbl_size = 
    (sizeof(app_gatt_db_ext_attr_tbl) / sizeof(gatt_db_lookup_table_t));

/* Number of GATT initial value arrays entries */
const uint16_t app_gap_device_name_len = 10;
const uint16_t app_gap_appearance_len = (sizeof(app_gap_appearance));
const uint16_t app_bas_battery_level_len = (sizeof(app_bas_battery_level));
const uint16_t app_bas_battery_level_char_presentation_format_len =
    (sizeof(app_bas_battery_level_char_presentation_format));
const uint16_t app_bas_battery_level_client_char_config_len =
    (sizeof(app_bas_battery_level_client_char_config));
