/**
 * @file  hal_gpio.c
 *
 * @brief Implementation of GPIO functions.
 *
 * @note PSOC63
 * 
 * @version 0.5.0
 */
#include "cy_pdl.h"
#include "cyhal.h"
#include "cy_gpio.h"

#include "hal_gpio.h"
#include "hal.h"

///////////////////////
// Defines
///////////////////////

///////////////////////
// Functions prototype
///////////////////////
static uint32_t _get_inputBuf_config(Hal_gpio_function_t func, Hal_gpio_pullRes_t pullRes);
static en_hsiom_sel_t _get_pinFunc_config(Hal_gpio_function_t func);

///////////////////////
// Private data
///////////////////////
/**
 * @note Default config for pin, 
 * typically the config is used to reset pin configuration (De-init).
 */
static const cy_stc_gpio_pin_config_t default_config =
{
    .outVal = 0,
    .driveMode = CY_GPIO_DM_ANALOG,
    .hsiom = HSIOM_SEL_GPIO,
    .intEdge = CY_GPIO_INTR_DISABLE,
    .intMask = 0UL,
    .vtrip = CY_GPIO_VTRIP_CMOS,
    .slewRate = CY_GPIO_SLEW_SLOW,
    .driveSel = CY_GPIO_DRIVE_1_8,
    .vregEn = 0UL,
    .ibufMode = 0UL,
    .vtripSel = 0UL,
    .vrefSel = 0UL,
    .vohSel = 0UL,
};

///////////////////////
// Code
///////////////////////
/**
 * @brief Initialize a pin with settings listed below. 
 * 
 * @param[in]   port    pointer to pin's Port data structure
 * 
 * @param[in]   pin     pin to init
 * 
 * @param[in]   func    pin function
 * 
 * @param[in]   pullRes pull resistor config
 * 
 * @param[in]   driveMode   output pin current drive setting
 * 
 * @param[in]   initialState    initial state LOW or HIGH
 * 
 * @note    \ref init_cycfg_pins() - Cypress autogenerated function + \ref Cy_GPIO_Pin_Init
 * 
 * @details High-impedance drive mode with input buffer disabled is also the default pin reset state.
 *          'Strong Drive' mode is used for digital output signals or to drive external devices.
 * 
 * @attention If a pin is connected only to an analog signal, the input
 *            buffer should be disabled to avoid crowbar currents.
 * 
 * @retval None
 * 
 */
void HAL_GPIO_init_pin(
    Hal_gpio_port_t* port, 
    Hal_gpio_pin_t pin,
    Hal_gpio_function_t func,
    Hal_gpio_pullRes_t pullRes,
    Hal_gpio_driveMode_t driveMode,
    Hal_gpio_pin_state_t initialState
)
{
    HAL_ASSERT(port != NULL);
    HAL_ASSERT(func <= HAL_GPIO_UART_TX);
    HAL_ASSERT(pullRes <= HAL_GPIO_PULL_DOWN);
    HAL_ASSERT(driveMode <= HAL_GPIO_DRIVE_HIGH);
    HAL_ASSERT(initialState <= HAL_GPIO_HIGH_LEVEL);

    cy_stc_gpio_pin_config_t pin_config;
    pin_config.outVal = initialState;

    /** Configure pin output/input buffer */
    if (driveMode == HAL_GPIO_DRIVE_HIGH) {
        // 'Strong Drive' output mode, without Pull resistors
        pin_config.driveMode = CY_GPIO_DM_STRONG_IN_OFF;
    } else if (driveMode == HAL_GPIO_DRIVE_NORMAL){
        // Config Pull-Up/Down for Output
        HAL_ASSERT(pullRes != HAL_GPIO_PULL_DISABLED);
        pin_config.driveMode = (pullRes ==HAL_GPIO_PULL_UP)? CY_GPIO_DM_PULLUP_IN_OFF: CY_GPIO_DM_PULLDOWN_IN_OFF;
    } else {
        // No output drive -> Input
        pin_config.driveMode = _get_inputBuf_config(func, pullRes);
    }

    /** Configure pin function (HSIOM) */
    pin_config.hsiom = _get_pinFunc_config(func);

    /** Configure other properties */
    pin_config.intEdge = CY_GPIO_INTR_DISABLE;
    pin_config.intMask = 0UL;
    pin_config.vtrip = CY_GPIO_VTRIP_CMOS;
    pin_config.slewRate = CY_GPIO_SLEW_FAST;
    pin_config.driveSel = CY_GPIO_DRIVE_1_2;
    pin_config.vregEn = 0UL;
    pin_config.ibufMode = 0UL;
    pin_config.vtripSel = 0UL;
    pin_config.vrefSel = 0UL;
    pin_config.vohSel = 0UL;

    /** Write configuration to the Registers */
    Cy_GPIO_Pin_Init(port, pin, &pin_config);
}

/**
 * @brief De-init a pin. 
 * 
 * @param[in]   port    pointer to pin's Port data structure
 * 
 * @param[in]   pin     pin to de-init
 * 
 * @details Set pin to High-Z mode but doesn't disable clock.
 * 
 * @retval None
 * 
 */
void HAL_GPIO_deinit_pin(Hal_gpio_port_t* port, Hal_gpio_pin_t pin)
{
    HAL_ASSERT(port != NULL);

    Cy_GPIO_Pin_Init(port, pin, &default_config);
}

/**
 * @brief Read a digital pin state.
 * 
 * @param[in]   port    pointer to pin's Port data structure
 * 
 * @param[in]   pin     pin to read
 * 
 * @retval HAL_GPIO_LOW_LEVEL or HAL_GPIO_HIGH_LEVEL
 * 
 */
Hal_gpio_pin_state_t HAL_GPIO_read_pin(Hal_gpio_port_t* port, Hal_gpio_pin_t pin)
{
    HAL_ASSERT(port != NULL);

    Hal_gpio_pin_state_t state = (Hal_gpio_pin_state_t) Cy_GPIO_Read(port, pin);

    return state;
}

/**
 * @brief Set a digital pin state. 
 * 
 * @param[in]   port    pointer to pin's Port data structure
 * 
 * @param[in]   pin     pin to set
 * 
 * @param[in]   level   LOW or HIGH
 * 
 * @retval HAL_GPIO_LOW_LEVEL or HAL_GPIO_HIGH_LEVEL
 * 
 */
void HAL_GPIO_set_pin(Hal_gpio_port_t* port, Hal_gpio_pin_t pin, Hal_gpio_pin_state_t level)
{
    HAL_ASSERT(port != NULL);
    HAL_ASSERT(level <= HAL_GPIO_HIGH_LEVEL);

    Cy_GPIO_Write(port, (uint32_t) pin, (uint32_t) level);
}

///////////////////////
// Auxiliary functions
///////////////////////
/**
 * @brief Determine input buffer configuration based on pin function (DIGITAL / ANALOG).
 * 
 * @param[in]   func    pin function
 * 
 * @param[in]   pullRes pull resistor config
 * 
 * @retval Input buffer config. \ref CY_GPIO_DM_ANALOG, CY_GPIO_DM_PULLUP etc.
 * 
 */
static uint32_t _get_inputBuf_config(Hal_gpio_function_t func, Hal_gpio_pullRes_t pullRes)
{
    uint32_t bufConfig;

    switch (func)
    {
        case HAL_GPIO_ANALOG_INPUT:
        {
            bufConfig = CY_GPIO_DM_ANALOG;
            break;
        }

        default:
        {
            // Not analog (digital) input
            if (pullRes == HAL_GPIO_PULL_DISABLED) {
                bufConfig = CY_GPIO_DM_HIGHZ;
            } else if (pullRes == HAL_GPIO_PULL_UP) {
                bufConfig = CY_GPIO_DM_PULLUP;
            } else if (pullRes == HAL_GPIO_PULL_DOWN) {
                bufConfig = CY_GPIO_DM_PULLDOWN;
            } else {
                // Invalid pull resistor configuration encountered in _get_inputBuf_config
                HAL_ASSERT(false);
                return CY_GPIO_DM_HIGHZ; // Return a safe default value
            }
            break;
        }
    }

    return bufConfig;
}

/**
 * @brief Determine Pin Function configuration (HSIOM) based on pin function.
 * 
 * @param[in]   func    pin function
 * 
 * @retval Pin function Config, \ref P10_0_GPIO, P10_0_SCB1_UART_RX etc.
 * 
 */
static en_hsiom_sel_t _get_pinFunc_config(Hal_gpio_function_t func)
{
    en_hsiom_sel_t hsiom_config;

    switch (func)
    {
        case HAL_GPIO_DIGITAL_OUTPUT:
        case HAL_GPIO_DIGITAL_INPUT:
        case HAL_GPIO_ANALOG_INPUT:
        {
            hsiom_config = HSIOM_SEL_GPIO;
            break;
        }

        case HAL_GPIO_UART_RX:
        {
            hsiom_config = P5_0_SCB5_UART_RX;
            break;
        }

        case HAL_GPIO_UART_TX:
        {
            hsiom_config = P5_1_SCB5_UART_TX;
            break;
        }

        default:
        {
            HAL_ASSERT(false);
            hsiom_config = HSIOM_SEL_GPIO; // Assign a safe default value
            break;
        }
    }

    return hsiom_config;
}

/* [] END OF FILE */
