#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
config device-configurator seglcd-configurator qspi-configurator config_usbdev usbdev-configurator capsense-configurator capsense-tuner bsp-assistant smartio-configurator modlibs library-manager config_ezpd ez-pd-configurator :
	make -C proj_cm4 $@

config_bt bt-configurator config_lin lin-configurator :
	$(error $@ configurator cannot be executed at the application level. Run this command from the desired project directory.)

.PHONY: config device-configurator config_bt bt-configurator seglcd-configurator qspi-configurator config_lin lin-configurator config_usbdev usbdev-configurator capsense-configurator capsense-tuner bsp-assistant smartio-configurator modlibs library-manager config_ezpd ez-pd-configurator
