/**
 * @file  hal_uart.c
 *
 * @brief Implementation of UART functions.
 *
 * @note PSOC63
 * 
 * @version 0.6.0
 */
#include "cy_pdl.h"
#include "cyhal.h"

#include "hal.h"
#include "hal_uart.h"

// ===================
// Code
// ===================
/**
 * @brief  Initialize UART
 * 
 * @details Configure & enable UART; Setup RX callback
 * 
 * @param[in] config - UART settings
 * 
 * @param[in]  callback - UART RX callback
 * 
 * @note 'config' isn't handled by the func, because BSP uses configuration
 *       generated by MTB tool (autogenerated code contains UART config object). 
 * 
 * @retval 0 - success, otherwise - fail status
 */
HAL_UART_status_t HAL_UART_init(HAL_UART_config_t *config, HAL_UART_rxCallback_t callback)
{
    HAL_ASSERT((config != NULL), __FILE__, __LINE__);

    HAL_UART_status_t status = HAL_UART_SUCCESS;
    bsp_status_init_t bsp_status = BSP_initUart(callback);
    if (bsp_status != bsp_status_init_success) {
        status = HAL_UART_FAIL;
    }

    return status;
}

/**
 * @brief  Check if UART TX FIFO is ready to receive data
 * 
 * @param  None
 * 
 * @retval true - UART is ready, false - not ready
 */
bool HAL_UART_isTxReady(void)
{
    return BSP_isUartTxReady();
}

/**
 * @brief  Transmit Raw data via UART
 * 
 * @param[in]   data - pointer to data buffer
 * 
 * @param[in]   len  - length of data
 * 
 * @retval None 
 */
void HAL_UART_txData(uint8_t *data, uint16_t len)
{
    HAL_ASSERT((data != NULL), __FILE__, __LINE__);
    HAL_ASSERT((len > 0), __FILE__, __LINE__);

    BSP_uartTxData(data, len); 
}

/**
 * @brief  Check if UART transmission is ongoing
 * 
 * @details Checks TX FIFO and transmit shift register status
 * 
 * @param  None
 * 
 * @retval true - TX is ongoing, false - no active transmission
 */
bool HAL_UART_isTxActive(void)
{
    return BSP_isUartTxActive();
}

/* [] END OF FILE */
