/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: QN908XC
package_id: QN9080C
mcu_data: ksdk2_0
processor_version: 24.12.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_iocon.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: '28', peripheral: FLEXCOMM0, signal: RXD, pin_signal: GPIOA17/CS3/SD_DAC/CTIMER2_MAT1/FC0_RXD/FC3_MISO/QDEC0_B}
  - {pin_num: '29', peripheral: FLEXCOMM0, signal: TXD, pin_signal: GPIOA16/CS2/SCT0_OUT1/CTIMER2_MAT0/FC0_TXD/FC3_MOSI/QDEC0_A}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{

    SYSCON->PIO_FUNC_CFG[2] = ((SYSCON->PIO_FUNC_CFG[2] &
                                /* Mask bits to zero which are setting */
                                (~(SYSCON_PIO_FUNC_CFG_PA16_FUNC_MASK | SYSCON_PIO_FUNC_CFG_PA17_FUNC_MASK)))

                               /* PORTA PIN16 (coords: 29) is configured as FC0_TXD. */
                               | SYSCON_PIO_FUNC_CFG_PA16_FUNC(PIO_FUNC_ALT4)

                               /* PORTA PIN17 (coords: 28) is configured as FC0_RXD. */
                               | SYSCON_PIO_FUNC_CFG_PA17_FUNC(PIO_FUNC_ALT4));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitButtons:
- options: {prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: '21', peripheral: GPIOA, signal: 'GPIOA, 24', pin_signal: GPIOA24/ACMP0N/CS6/ETM_TRACEDAT0/CTIMER3_CAP0/RFE_RX_EN/FC3_SSEL1/SPIFI_IO0, direction: INPUT,
    pull_control: Pull_up, drive_strength: low}
  - {pin_num: '26', peripheral: GPIOA, signal: 'GPIOA, 19', pin_signal: GPIOA19/CS5/SCT0_OUT2/RFE_EN/FC0_SCK/FC3_SSEL3/BLE_IN_PROC, direction: INPUT, pull_control: Pull_up,
    drive_strength: low, drive_extra: disabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitButtons
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitButtons(void)
{
    /* Enables the clock for the GPIO module */
    CLOCK_EnableClock(kCLOCK_Gpio);

    gpio_pin_config_t gpioa_pin26_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin GPIOA19 (pin 26) */
    GPIO_PinInit(GPIOA, 19U, &gpioa_pin26_config);

    gpio_pin_config_t gpioa_pin21_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin GPIOA24 (pin 21) */
    GPIO_PinInit(GPIOA, 24U, &gpioa_pin21_config);
    const uint32_t portA_pin19_config = (/* Selects pin function 0 */
                                         IOCON_FUNC0 |
                                         /* Selects pull-up function */
                                         IOCON_MODE_PULLUP |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 19 (coords: 26) is configured as GPIOA19 */
    IOCON_PinMuxSet(IOCON, 0U, 19U, portA_pin19_config);

    const uint32_t portA_pin24_config = (/* Selects pin function 0 */
                                         IOCON_FUNC0 |
                                         /* Selects pull-up function */
                                         IOCON_MODE_PULLUP |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 24 (coords: 21) is configured as GPIOA24 */
    IOCON_PinMuxSet(IOCON, 0U, 24U, portA_pin24_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLEDs:
- options: {prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: '12', peripheral: GPIOA, signal: 'GPIOA, 31', pin_signal: GPIOA31/DAC/RTC_CAP/CTIMER3_MAT2/SWO/FC3_SCK/SPIFI_CLK, direction: OUTPUT, pull_control: Pull_up,
    drive_strength: low}
  - {pin_num: '32', peripheral: GPIOA, signal: 'GPIOA, 13', pin_signal: GPIOA13/SCT0_OUT4/ACMP1_OUT/FC1_RXD_SDA/FC3_SSEL1/RFE_EN, direction: OUTPUT, pull_control: Pull_up,
    drive_strength: low}
  - {pin_num: '20', peripheral: GPIOA, signal: 'GPIOA, 25', pin_signal: GPIOA25/ACMP0P/CS7/ETM_TRACEDAT1/CTIMER3_CAP1/RFE_TX_EN/FC3_SSEL0/SPIFI_IO1, direction: OUTPUT,
    pull_control: Pull_up, drive_strength: low}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLEDs
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLEDs(void)
{
    /* Enables the clock for the GPIO module */
    CLOCK_EnableClock(kCLOCK_Gpio);

    gpio_pin_config_t gpioa_pin32_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin GPIOA13 (pin 32) */
    GPIO_PinInit(GPIOA, 13U, &gpioa_pin32_config);

    gpio_pin_config_t gpioa_pin20_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin GPIOA25 (pin 20) */
    GPIO_PinInit(GPIOA, 25U, &gpioa_pin20_config);

    gpio_pin_config_t gpioa_pin12_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin GPIOA31 (pin 12) */
    GPIO_PinInit(GPIOA, 31U, &gpioa_pin12_config);
    const uint32_t portA_pin13_config = (/* Selects pin function 0 */
                                         IOCON_FUNC0 |
                                         /* Selects pull-up function */
                                         IOCON_MODE_PULLUP |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 13 (coords: 32) is configured as GPIOA13 */
    IOCON_PinMuxSet(IOCON, 0U, 13U, portA_pin13_config);

    const uint32_t portA_pin25_config = (/* Selects pin function 0 */
                                         IOCON_FUNC0 |
                                         /* Selects pull-up function */
                                         IOCON_MODE_PULLUP |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 25 (coords: 20) is configured as GPIOA25 */
    IOCON_PinMuxSet(IOCON, 0U, 25U, portA_pin25_config);

    const uint32_t portA_pin31_config = (/* Selects pin function 0 */
                                         IOCON_FUNC0 |
                                         /* Selects pull-up function */
                                         IOCON_MODE_PULLUP |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 31 (coords: 12) is configured as GPIOA31 */
    IOCON_PinMuxSet(IOCON, 0U, 31U, portA_pin31_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDEBUG_UART:
- options: {prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: '29', peripheral: FLEXCOMM0, signal: TXD, pin_signal: GPIOA16/CS2/SCT0_OUT1/CTIMER2_MAT0/FC0_TXD/FC3_MOSI/QDEC0_A, pull_control: High_Z, drive_strength: low}
  - {pin_num: '28', peripheral: FLEXCOMM0, signal: RXD, pin_signal: GPIOA17/CS3/SD_DAC/CTIMER2_MAT1/FC0_RXD/FC3_MISO/QDEC0_B, pull_control: High_Z, drive_strength: low}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDEBUG_UART
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitDEBUG_UART(void)
{
    const uint32_t portA_pin16_config = (/* Selects pin function 4 */
                                         IOCON_FUNC4 |
                                         /* Selects High-Z function */
                                         IOCON_MODE_HIGHZ |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 16 (coords: 29) is configured as FC0_TXD */
    IOCON_PinMuxSet(IOCON, 0U, 16U, portA_pin16_config);

    const uint32_t portA_pin17_config = (/* Selects pin function 4 */
                                         IOCON_FUNC4 |
                                         /* Selects High-Z function */
                                         IOCON_MODE_HIGHZ |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 17 (coords: 28) is configured as FC0_RXD */
    IOCON_PinMuxSet(IOCON, 0U, 17U, portA_pin17_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPMod_SPI_I2C:
- options: {prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: '4', peripheral: FLEXCOMM1, signal: CTS_SDA, pin_signal: GPIOA7/ADC_VREFI/SCT0_OUT2/CTIMER1_CAP0/FC1_CTS_SDA/BLE_PTI1/SPIFI_CSN, pull_control: High_Z,
    drive_strength: low}
  - {pin_num: '5', peripheral: FLEXCOMM1, signal: RTS_SCL, pin_signal: GPIOA6/SCT0_OUT3/CTIMER0_MAT2/FC1_RTS_SCL/BLE_PTI0/SPIFI_CLK, pull_control: High_Z, drive_strength: low,
    drive_extra: disabled}
  - {pin_num: '6', peripheral: FLEXCOMM2, signal: SCL_MISO, pin_signal: GPIOA5/ADC3/SCT0_OUT5/CTIMER0_MAT1/FC0_RXD/FC2_SCL_MISO/SPIFI_IO1, pull_control: High_Z, drive_strength: low}
  - {pin_num: '7', peripheral: FLEXCOMM2, signal: SDA_MOSI, pin_signal: GPIOA4/ADC2/SCT0_OUT4/CTIMER0_MAT0/FC0_TXD/FC2_SDA_MOSI/SPIFI_IO0, pull_control: High_Z, drive_strength: low}
  - {pin_num: '8', peripheral: FLEXCOMM2, signal: SDA_SSEL0, pin_signal: GPIOA3/QDEC0_B/SCT0_OUT3/CTIMER0_MAT1/FC2_SDA_SSEL0/RFE_TX_EN, pull_control: High_Z, drive_strength: low}
  - {pin_num: '15', peripheral: FLEXCOMM2, signal: SCK, pin_signal: GPIOA30/ACMP1P/ETM_TRACEDAT3/CTIMER3_MAT1/FC2_SCK/FC3_MOSI/SPIFI_IO3, pull_control: High_Z, drive_strength: low}
  - {pin_num: '33', peripheral: GPIOB, signal: 'GPIOB, 2', pin_signal: GPIOB2/ANT_SW, pull_control: High_Z, drive_strength: low}
  - {pin_num: '12', peripheral: FLEXCOMM3, signal: SCK, pin_signal: GPIOA31/DAC/RTC_CAP/CTIMER3_MAT2/SWO/FC3_SCK/SPIFI_CLK, pull_control: High_Z, drive_strength: low}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPMod_SPI_I2C
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPMod_SPI_I2C(void)
{
    const uint32_t portA_pin3_config = (/* Selects pin function 5 */
                                        IOCON_FUNC5 |
                                        /* Selects High-Z function */
                                        IOCON_MODE_HIGHZ |
                                        /* Enable low drive strength */
                                        IOCON_DRIVE_LOW);
    /* PORTA PIN 3 (coords: 8) is configured as FC2_SDA_SSEL0 */
    IOCON_PinMuxSet(IOCON, 0U, 3U, portA_pin3_config);

    const uint32_t portA_pin4_config = (/* Selects pin function 5 */
                                        IOCON_FUNC5 |
                                        /* Selects High-Z function */
                                        IOCON_MODE_HIGHZ |
                                        /* Enable low drive strength */
                                        IOCON_DRIVE_LOW);
    /* PORTA PIN 4 (coords: 7) is configured as FC2_SDA_MOSI */
    IOCON_PinMuxSet(IOCON, 0U, 4U, portA_pin4_config);

    const uint32_t portA_pin5_config = (/* Selects pin function 5 */
                                        IOCON_FUNC5 |
                                        /* Selects High-Z function */
                                        IOCON_MODE_HIGHZ |
                                        /* Enable low drive strength */
                                        IOCON_DRIVE_LOW);
    /* PORTA PIN 5 (coords: 6) is configured as FC2_SCL_MISO */
    IOCON_PinMuxSet(IOCON, 0U, 5U, portA_pin5_config);

    const uint32_t portA_pin6_config = (/* Selects pin function 4 */
                                        IOCON_FUNC4 |
                                        /* Selects High-Z function */
                                        IOCON_MODE_HIGHZ |
                                        /* Enable low drive strength */
                                        IOCON_DRIVE_LOW);
    /* PORTA PIN 6 (coords: 5) is configured as FC1_RTS_SCL */
    IOCON_PinMuxSet(IOCON, 0U, 6U, portA_pin6_config);

    const uint32_t portA_pin7_config = (/* Selects pin function 4 */
                                        IOCON_FUNC4 |
                                        /* Selects High-Z function */
                                        IOCON_MODE_HIGHZ |
                                        /* Enable low drive strength */
                                        IOCON_DRIVE_LOW);
    /* PORTA PIN 7 (coords: 4) is configured as FC1_CTS_SDA */
    IOCON_PinMuxSet(IOCON, 0U, 7U, portA_pin7_config);

    const uint32_t portA_pin30_config = (/* Selects pin function 4 */
                                         IOCON_FUNC4 |
                                         /* Selects High-Z function */
                                         IOCON_MODE_HIGHZ |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 30 (coords: 15) is configured as FC2_SCK */
    IOCON_PinMuxSet(IOCON, 0U, 30U, portA_pin30_config);

    const uint32_t portA_pin31_config = (/* Selects pin function 5 */
                                         IOCON_FUNC5 |
                                         /* Selects High-Z function */
                                         IOCON_MODE_HIGHZ |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 31 (coords: 12) is configured as FC3_SCK */
    IOCON_PinMuxSet(IOCON, 0U, 31U, portA_pin31_config);
    const uint32_t portB_pin2_config = (/* Selects pin function 0 */
                                        IOCON_FUNC0 |
                                        /* Selects High-Z function */
                                        IOCON_MODE_HIGHZ |
                                        /* Enable low drive strength */
                                        IOCON_DRIVE_LOW);
    /* PORTB PIN 2 (coords: 33) is configured as GPIOB2 */
    IOCON_PinMuxSet(IOCON, 1U, 2U, portB_pin2_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSWD_DEBUG:
- options: {prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: '23', peripheral: SWD, signal: SWCLK, pin_signal: SWCLK/GPIOA22/SCT0_IN2/CTIMER3_MAT0/FC2_SDA_SSEL0/FC3_SSEL3/QDEC1_A, pull_control: Pull_down, drive_strength: low}
  - {pin_num: '22', peripheral: SWD, signal: SWDIO, pin_signal: SWDIO/GPIOA23/SCT0_IN3/CTIMER3_MAT1/FC2_SCL_SSEL1/FC3_SSEL2/QDEC1_B, pull_control: High_Z, drive_strength: low}
  - {pin_num: '12', peripheral: SWD, signal: SWO, pin_signal: GPIOA31/DAC/RTC_CAP/CTIMER3_MAT2/SWO/FC3_SCK/SPIFI_CLK, pull_control: High_Z, drive_strength: low}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSWD_DEBUG
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitSWD_DEBUG(void)
{
    const uint32_t portA_pin22_config = (/* Selects pin function 0 */
                                         IOCON_FUNC0 |
                                         /* Selects pull-down function */
                                         IOCON_MODE_PULLDOWN |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 22 (coords: 23) is configured as SWCLK */
    IOCON_PinMuxSet(IOCON, 0U, 22U, portA_pin22_config);

    const uint32_t portA_pin23_config = (/* Selects pin function 0 */
                                         IOCON_FUNC0 |
                                         /* Selects High-Z function */
                                         IOCON_MODE_HIGHZ |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 23 (coords: 22) is configured as SWDIO */
    IOCON_PinMuxSet(IOCON, 0U, 23U, portA_pin23_config);

    const uint32_t portA_pin31_config = (/* Selects pin function 4 */
                                         IOCON_FUNC4 |
                                         /* Selects High-Z function */
                                         IOCON_MODE_HIGHZ |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 31 (coords: 12) is configured as SWO */
    IOCON_PinMuxSet(IOCON, 0U, 31U, portA_pin31_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitETM_TRACE:
- options: {prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: '16', peripheral: ETM, signal: 'ETM_TRACEDATA, 2', pin_signal: GPIOA29/ACMP1N/ETM_TRACEDAT2/CTIMER3_MAT0/FC2_SCK/FC3_MISO/SPIFI_IO2, pull_control: High_Z,
    drive_strength: low}
  - {pin_num: '17', peripheral: ETM, signal: ETM_TRACECLK, pin_signal: GPIOA28/CLK_AHB/ETM_TRACECLK/RTC_CAP/FC1_SCK/SD_DAC/SPIFI_CSN, pull_control: High_Z, drive_strength: low}
  - {pin_num: '15', peripheral: ETM, signal: 'ETM_TRACEDATA, 3', pin_signal: GPIOA30/ACMP1P/ETM_TRACEDAT3/CTIMER3_MAT1/FC2_SCK/FC3_MOSI/SPIFI_IO3, pull_control: High_Z,
    drive_strength: low}
  - {pin_num: '21', peripheral: ETM, signal: 'ETM_TRACEDATA, 0', pin_signal: GPIOA24/ACMP0N/CS6/ETM_TRACEDAT0/CTIMER3_CAP0/RFE_RX_EN/FC3_SSEL1/SPIFI_IO0, pull_control: High_Z,
    drive_strength: low}
  - {pin_num: '20', peripheral: ETM, signal: 'ETM_TRACEDATA, 1', pin_signal: GPIOA25/ACMP0P/CS7/ETM_TRACEDAT1/CTIMER3_CAP1/RFE_TX_EN/FC3_SSEL0/SPIFI_IO1, pull_control: High_Z,
    drive_strength: low}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitETM_TRACE
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitETM_TRACE(void)
{
    const uint32_t portA_pin24_config = (/* Selects pin function 2 */
                                         IOCON_FUNC2 |
                                         /* Selects High-Z function */
                                         IOCON_MODE_HIGHZ |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 24 (coords: 21) is configured as ETM_TRACEDAT0 */
    IOCON_PinMuxSet(IOCON, 0U, 24U, portA_pin24_config);

    const uint32_t portA_pin25_config = (/* Selects pin function 2 */
                                         IOCON_FUNC2 |
                                         /* Selects High-Z function */
                                         IOCON_MODE_HIGHZ |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 25 (coords: 20) is configured as ETM_TRACEDAT1 */
    IOCON_PinMuxSet(IOCON, 0U, 25U, portA_pin25_config);

    const uint32_t portA_pin28_config = (/* Selects pin function 2 */
                                         IOCON_FUNC2 |
                                         /* Selects High-Z function */
                                         IOCON_MODE_HIGHZ |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 28 (coords: 17) is configured as ETM_TRACECLK */
    IOCON_PinMuxSet(IOCON, 0U, 28U, portA_pin28_config);

    const uint32_t portA_pin29_config = (/* Selects pin function 2 */
                                         IOCON_FUNC2 |
                                         /* Selects High-Z function */
                                         IOCON_MODE_HIGHZ |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 29 (coords: 16) is configured as ETM_TRACEDAT2 */
    IOCON_PinMuxSet(IOCON, 0U, 29U, portA_pin29_config);

    const uint32_t portA_pin30_config = (/* Selects pin function 2 */
                                         IOCON_FUNC2 |
                                         /* Selects High-Z function */
                                         IOCON_MODE_HIGHZ |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 30 (coords: 15) is configured as ETM_TRACEDAT3 */
    IOCON_PinMuxSet(IOCON, 0U, 30U, portA_pin30_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitUSB:
- options: {prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: '18', peripheral: USB0, signal: USB_DM, pin_signal: GPIOA27/USB_DM/SCT0_IN1/CTIMER1_MAT2/FC2_SCL_MISO/QDEC0_B/BLE_IN_PROC, pull_control: High_Z, drive_strength: low,
    drive_extra: disabled}
  - {pin_num: '19', peripheral: USB0, signal: USB_DP, pin_signal: GPIOA26/USB_DP/SCT0_IN0/CTIMER1_MAT0/FC2_SDA_MOSI/QDEC0_A/BLE_SYNC, pull_control: High_Z, drive_strength: low,
    drive_extra: disabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitUSB
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitUSB(void)
{
    const uint32_t portA_pin26_config = (/* Selects pin function 1 */
                                         IOCON_FUNC1 |
                                         /* Selects High-Z function */
                                         IOCON_MODE_HIGHZ |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 26 (coords: 19) is configured as USB_DP */
    IOCON_PinMuxSet(IOCON, 0U, 26U, portA_pin26_config);

    const uint32_t portA_pin27_config = (/* Selects pin function 1 */
                                         IOCON_FUNC1 |
                                         /* Selects High-Z function */
                                         IOCON_MODE_HIGHZ |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 27 (coords: 18) is configured as USB_DM */
    IOCON_PinMuxSet(IOCON, 0U, 27U, portA_pin27_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitG_Sensor:
- options: {prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: '5', peripheral: FLEXCOMM1, signal: RTS_SCL, pin_signal: GPIOA6/SCT0_OUT3/CTIMER0_MAT2/FC1_RTS_SCL/BLE_PTI0/SPIFI_CLK, pull_control: High_Z, drive_strength: low,
    drive_extra: disabled}
  - {pin_num: '4', peripheral: FLEXCOMM1, signal: CTS_SDA, pin_signal: GPIOA7/ADC_VREFI/SCT0_OUT2/CTIMER1_CAP0/FC1_CTS_SDA/BLE_PTI1/SPIFI_CSN, pull_control: High_Z,
    drive_strength: low}
  - {pin_num: '31', peripheral: GPIOA, signal: 'GPIOA, 14', pin_signal: GPIOA14/CS0/ANT_SW/CTIMER2_CAP0/FC0_RTS/FC3_SSEL0/QDEC1_A, pull_control: High_Z, drive_strength: low}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitG_Sensor
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitG_Sensor(void)
{
    const uint32_t portA_pin6_config = (/* Selects pin function 4 */
                                        IOCON_FUNC4 |
                                        /* Selects High-Z function */
                                        IOCON_MODE_HIGHZ |
                                        /* Enable low drive strength */
                                        IOCON_DRIVE_LOW);
    /* PORTA PIN 6 (coords: 5) is configured as FC1_RTS_SCL */
    IOCON_PinMuxSet(IOCON, 0U, 6U, portA_pin6_config);

    const uint32_t portA_pin7_config = (/* Selects pin function 4 */
                                        IOCON_FUNC4 |
                                        /* Selects High-Z function */
                                        IOCON_MODE_HIGHZ |
                                        /* Enable low drive strength */
                                        IOCON_DRIVE_LOW);
    /* PORTA PIN 7 (coords: 4) is configured as FC1_CTS_SDA */
    IOCON_PinMuxSet(IOCON, 0U, 7U, portA_pin7_config);

    const uint32_t portA_pin14_config = (/* Selects pin function 0 */
                                         IOCON_FUNC0 |
                                         /* Selects High-Z function */
                                         IOCON_MODE_HIGHZ |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 14 (coords: 31) is configured as GPIOA14 */
    IOCON_PinMuxSet(IOCON, 0U, 14U, portA_pin14_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSPI_FLASH:
- options: {prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: '8', peripheral: FLEXCOMM2, signal: SDA_SSEL0, pin_signal: GPIOA3/QDEC0_B/SCT0_OUT3/CTIMER0_MAT1/FC2_SDA_SSEL0/RFE_TX_EN, pull_control: High_Z, drive_strength: low}
  - {pin_num: '6', peripheral: FLEXCOMM2, signal: SCL_MISO, pin_signal: GPIOA5/ADC3/SCT0_OUT5/CTIMER0_MAT1/FC0_RXD/FC2_SCL_MISO/SPIFI_IO1, pull_control: High_Z, drive_strength: low}
  - {pin_num: '7', peripheral: FLEXCOMM2, signal: SDA_MOSI, pin_signal: GPIOA4/ADC2/SCT0_OUT4/CTIMER0_MAT0/FC0_TXD/FC2_SDA_MOSI/SPIFI_IO0, pull_control: High_Z, drive_strength: low}
  - {pin_num: '15', peripheral: FLEXCOMM2, signal: SCK, pin_signal: GPIOA30/ACMP1P/ETM_TRACEDAT3/CTIMER3_MAT1/FC2_SCK/FC3_MOSI/SPIFI_IO3, pull_control: High_Z, drive_strength: low}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSPI_FLASH
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitSPI_FLASH(void)
{
    const uint32_t portA_pin3_config = (/* Selects pin function 5 */
                                        IOCON_FUNC5 |
                                        /* Selects High-Z function */
                                        IOCON_MODE_HIGHZ |
                                        /* Enable low drive strength */
                                        IOCON_DRIVE_LOW);
    /* PORTA PIN 3 (coords: 8) is configured as FC2_SDA_SSEL0 */
    IOCON_PinMuxSet(IOCON, 0U, 3U, portA_pin3_config);

    const uint32_t portA_pin4_config = (/* Selects pin function 5 */
                                        IOCON_FUNC5 |
                                        /* Selects High-Z function */
                                        IOCON_MODE_HIGHZ |
                                        /* Enable low drive strength */
                                        IOCON_DRIVE_LOW);
    /* PORTA PIN 4 (coords: 7) is configured as FC2_SDA_MOSI */
    IOCON_PinMuxSet(IOCON, 0U, 4U, portA_pin4_config);

    const uint32_t portA_pin5_config = (/* Selects pin function 5 */
                                        IOCON_FUNC5 |
                                        /* Selects High-Z function */
                                        IOCON_MODE_HIGHZ |
                                        /* Enable low drive strength */
                                        IOCON_DRIVE_LOW);
    /* PORTA PIN 5 (coords: 6) is configured as FC2_SCL_MISO */
    IOCON_PinMuxSet(IOCON, 0U, 5U, portA_pin5_config);

    const uint32_t portA_pin30_config = (/* Selects pin function 4 */
                                         IOCON_FUNC4 |
                                         /* Selects High-Z function */
                                         IOCON_MODE_HIGHZ |
                                         /* Enable low drive strength */
                                         IOCON_DRIVE_LOW);
    /* PORTA PIN 30 (coords: 15) is configured as FC2_SCK */
    IOCON_PinMuxSet(IOCON, 0U, 30U, portA_pin30_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSPI:
- options: {coreID: cm4}
- pin_list:
  - {pin_num: '16', peripheral: FLEXCOMM2, signal: SCK, pin_signal: GPIOA29/ACMP1N/ETM_TRACEDAT2/CTIMER3_MAT0/FC2_SCK/FC3_MISO/SPIFI_IO2}
  - {pin_num: '18', peripheral: FLEXCOMM2, signal: SCL_MISO, pin_signal: GPIOA27/USB_DM/SCT0_IN1/CTIMER1_MAT2/FC2_SCL_MISO/QDEC0_B/BLE_IN_PROC}
  - {pin_num: '22', peripheral: FLEXCOMM2, signal: SCL_SSEL1, pin_signal: SWDIO/GPIOA23/SCT0_IN3/CTIMER3_MAT1/FC2_SCL_SSEL1/FC3_SSEL2/QDEC1_B}
  - {pin_num: '19', peripheral: FLEXCOMM2, signal: SDA_MOSI, pin_signal: GPIOA26/USB_DP/SCT0_IN0/CTIMER1_MAT0/FC2_SDA_MOSI/QDEC0_A/BLE_SYNC}
  - {pin_num: '23', peripheral: FLEXCOMM2, signal: SDA_SSEL0, pin_signal: SWCLK/GPIOA22/SCT0_IN2/CTIMER3_MAT0/FC2_SDA_SSEL0/FC3_SSEL3/QDEC1_A}
  - {pin_num: '43', peripheral: FLEXCOMM2, signal: SSEL2, pin_signal: GPIOA11/ADC7/SCT0_IN3/CTIMER1_MAT2/FC2_SSEL2/ACMP1_OUT/BLE_RX}
  - {pin_num: '24', peripheral: FLEXCOMM2, signal: SSEL3, pin_signal: GPIOA21/QDEC1_B/SCT0_OUT0/CTIMER2_MAT1/FC2_SSEL3/FC1_CTS_SDA/SPIFI_CSN}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSPI
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitSPI(void)
{

    SYSCON->PIO_FUNC_CFG[1] = ((SYSCON->PIO_FUNC_CFG[1] &
                                /* Mask bits to zero which are setting */
                                (~(SYSCON_PIO_FUNC_CFG_PA11_FUNC_MASK)))

                               /* PORTA PIN11 (coords: 43) is configured as FC2_SSEL2. */
                               | SYSCON_PIO_FUNC_CFG_PA11_FUNC(PIO_FUNC_ALT4));

    SYSCON->PIO_FUNC_CFG[2] =
        ((SYSCON->PIO_FUNC_CFG[2] &
          /* Mask bits to zero which are setting */
          (~(SYSCON_PIO_FUNC_CFG_PA21_FUNC_MASK | SYSCON_PIO_FUNC_CFG_PA22_FUNC_MASK | SYSCON_PIO_FUNC_CFG_PA23_FUNC_MASK)))

         /* PORTA PIN21 (coords: 24) is configured as FC2_SSEL3. */
         | SYSCON_PIO_FUNC_CFG_PA21_FUNC(PIO_FUNC_ALT4)

         /* PORTA PIN22 (coords: 23) is configured as FC2_SDA_SSEL0. */
         | SYSCON_PIO_FUNC_CFG_PA22_FUNC(PIO_FUNC_ALT4)

         /* PORTA PIN23 (coords: 22) is configured as FC2_SCL_SSEL1. */
         | SYSCON_PIO_FUNC_CFG_PA23_FUNC(PIO_FUNC_ALT4));

    SYSCON->PIO_FUNC_CFG[3] =
        ((SYSCON->PIO_FUNC_CFG[3] &
          /* Mask bits to zero which are setting */
          (~(SYSCON_PIO_FUNC_CFG_PA26_FUNC_MASK | SYSCON_PIO_FUNC_CFG_PA27_FUNC_MASK | SYSCON_PIO_FUNC_CFG_PA29_FUNC_MASK)))

         /* PORTA PIN26 (coords: 19) is configured as FC2_SDA_MOSI. */
         | SYSCON_PIO_FUNC_CFG_PA26_FUNC(PIO_FUNC_ALT4)

         /* PORTA PIN27 (coords: 18) is configured as FC2_SCL_MISO. */
         | SYSCON_PIO_FUNC_CFG_PA27_FUNC(PIO_FUNC_ALT4)

         /* PORTA PIN29 (coords: 16) is configured as FC2_SCK. */
         | SYSCON_PIO_FUNC_CFG_PA29_FUNC(PIO_FUNC_ALT4));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
